#!/bin/sh

set -x

DEFAULT_MOUNT="test"


# 未传入参数LOCATION
if [ "x$LOCATION" == "x" ]&&[ "x$DEV" != "x" ];then
if [ -a /root/$DEFAULT_MOUNT ];then
mount $DEV /root/$DEFAULT_MOUNT
cat >/etc/supervisord.d/test.conf <<EOF
[program:tomcat]
command=/tomcat/bin/catalina.sh run
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/tomcat_out.log
stderr_logfile=/var/log/supervisor/tomcat_err.log

EOF
exec /usr/bin/supervisord -n
exit
else
mkdir -p /root/$DEFAULT_MOUNT
mount $DEV /root/$DEFAULT_MOUNT
cat >/etc/supervisord.d/test.conf <<EOF
[program:tomcat]
command=/tomcat/bin/catalina.sh run
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/tomcat_out.log
stderr_logfile=/var/log/supervisor/tomcat_err.log

EOF
exec /usr/bin/supervisord -n
exit
fi
fi


#未传入参数DEV
if [ "x$LOCATION" != "x" ]&&[ "x$DEV" == "x" ];then
cat >/etc/supervisord.d/test.conf <<EOF
[program:tomcat]
command=/tomcat/bin/catalina.sh run
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/tomcat_out.log
stderr_logfile=/var/log/supervisor/tomcat_err.log

EOF
exec /usr/bin/supervisord -n
exit
fi



#DEV和LOCATION都传入
if [ "x$LOCATION" != "x" ]&&[ "x$DEV" != "x" ];then
if [ -a $LOCATION ];then
mount $DEV $LOCATION
echo "init disk"
echo "init service configure"
cat >/etc/supervisord.d/test.conf <<EOF
[program:tomcat]
command=/tomcat/bin/catalina.sh run
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/tomcat_out.log
stderr_logfile=/var/log/supervisor/tomcat_err.log

EOF
exec /usr/bin/supervisord -n
exit
else
mkdir -p $LOCATION
mount $DEV $LOCATION
echo "init disk"
echo "init service configure"
cat >/etc/supervisord.d/test.conf <<EOF
[program:tomcat]
command=/tomcat/bin/catalina.sh run
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/tomcat_out.log
stderr_logfile=/var/log/supervisor/tomcat_err.log

EOF
exec /usr/bin/supervisord -n
exit
fi
fi

if [ "x$LOCATION" == "x" ]&&[ "x$DEV" == "x" ];then
cat >/etc/supervisord.d/test.conf <<EOF
[program:tomcat]
command=/tomcat/bin/catalina.sh run
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/tomcat_out.log
stderr_logfile=/var/log/supervisor/tomcat_err.log

EOF
exec /usr/bin/supervisord -n
exit
fi

